### ISSUE TITLE
编译报错，是什么原因？

### ISSUE THREAD

**Issue by yangkangka** [baidu/babylon#12]
![image](https://github.com/baidu/babylon/assets/78491464/00863a9f-db1e-417d-bbf0-252830b6615f)

**Comment by oathdruid** [comment]
bazel用的版本是？

**Comment by yangkangka** [comment]
<img width="195" alt="image" src="https://github.com/baidu/babylon/assets/78491464/0460fd9e-d6bf-4bf1-bdc6-5fd05ecc01ba">

**Comment by oathdruid** [comment]
看起来比较老了，后续准备main切到更新的bzlmod模式，到时候可能会需要更高的版本了；直接用bazelisk下一个推荐的新版7.1.1试试看？

**Comment by yangkangka** [comment]
<img width="794" alt="image" src="https://github.com/baidu/babylon/assets/78491464/a8175297-1239-4966-9685-d5c1bb27910f">
需要升级gcc吗？

**Comment by yangkangka** [comment]
![image](https://github.com/baidu/babylon/assets/78491464/4a9beb95-ef4c-4600-9196-3c59f50c109c)
现在出现这个报错

**Comment by oathdruid** [comment]
- 默认需要支持c++17的编译器，不过baidu内部也有使用c++11的场景，如果确实需要低版本支持，需要修改.bazelrc里面的设置，对应的absl版本也要降级；所以可以的话还是升级到支持c++17的编译器更好

- 看你本地存在cmake的build目录了，需要整体清理一下，不然用...会匹配到所有包含bazel相关文件的目录；或明确使用bazel build src/... 或者bazel test test/...会更不容易被其他目录干扰

**Comment by yangkangka** [comment]
<img width="447" alt="image" src="https://github.com/baidu/babylon/assets/78491464/bbca8055-7811-4ec0-8ab6-5882018ae12c">
.bazelrc 中需要改这个字段吗？
absl版本降级需要在哪里修改？

**Comment by yangkangka** [comment]
boost总是下载到1.5 MiB后失败，报错GET returned 401 Unauthorized，遇到过吗？

**Comment by oathdruid** [comment]
abseil-cpp最后一个支持c++14的LTS应该是20220623.1，对应的gtest和protobuf的版本也要改，其实用google全家桶不如升一下编译器

boost下载确实慢，也可以找个其他网好的环境下载好然后拷贝到bazel的cache里，不过需要学习一下bazel cache的目录结构

**Comment by yangkangka** [comment]
使用cmake编译后如何将头文件和库文件输出到output目录？

**Comment by yangkangka** [comment]
有没有类似brpc中的example？ 可以查看接口怎么使用

**Comment by oathdruid** [comment]
CMake支持几类典型用法，分别加了一些例子在https://github.com/baidu/babylon/tree/main/example
首页的[Readme](https://github.com/baidu/babylon/tree/main?tab=readme-ov-file#cmake)里该写成了按照依赖使用的步骤

**Comment by yangkangka** [comment]
<img width="602" alt="image" src="https://github.com/baidu/babylon/assets/78491464/5c0ef951-1628-4225-bbfd-66d2f1dd8377">
depend-use-cmake-subdir 的编译出现报错，cmakelist 需要改什么吗？

**Comment by oathdruid** [comment]
subdir这个得准备源码到本地目录，分别放到对应名字的，我再在build.sh里面加一些wget环境准备吧，更直观一些
