### ISSUE TITLE
future 默认的SchedInterface能在bthread环境下使用吗

### ISSUE THREAD

**Issue by wanghenshui** [baidu/babylon#22]
使用模板参数支持自定义SchedInterface，支持在bthread等协程环境使用

这里是需要自己实现bthread环境下的SchedInterface，还是说本来就可以

https://github.com/baidu/babylon/blob/f7c55afaa896b5eb60e0f8c9b12b045ad1167dbd/docs/future.md?plain=1#L7

**Comment by oathdruid** [comment]
单纯说能不能用，是能用的，就像pthread的其他原语在协程环境下也可以有条件使用，需要自己注意上下文切换时机以及协程worker被阻塞的风险

不过实际上确实内部是使用ButexInterface来进行使用的，bthread留的调度接口非常futex like，所以其实很好封装一套出来

**Comment by wanghenshui** [comment]
> 单纯说能不能用，是能用的，就像pthread的其他原语在协程环境下也可以有条件使用，需要自己注意上下文切换时机以及协程worker被阻塞的风险
> 
> 不过实际上确实内部是使用ButexInterface来进行使用的，bthread留的调度接口非常futex like，所以其实很好封装一套出来

应该是不行，异步发送rpc 回调里set_value 外面用future wait，直接卡死了。都在futex wait

**Comment by oathdruid** [comment]
在bthread环境要安全用到阻塞的功能，也需要封装一个对应的executor，同步原语换对应的interface

感觉那有时间我也做个example把这个模式的样例放出来吧

**Comment by oathdruid** [comment]
@wanghenshui https://github.com/baidu/babylon/tree/main/example/use-with-bthread
做了个例子，把内部用的封装bthread环境的那个简单包装也放在这了

**Comment by wanghenshui** [comment]
> @wanghenshui https://github.sheincorp.cn/baidu/babylon/tree/main/example/use-with-bthread 做了个例子，把内部用的封装bthread环境的那个简单包装也放在这了

ok
