### ISSUE TITLE
ubuntu22.04下编译会有问题

### ISSUE THREAD

**Issue by EvanLyu732** [baidu/babylon#40]
默认的protoc版本是多少

- OS: ubuntu22.04
- protoc: libprotoc 3.20.3
- 构建工具: cmake

错误日志: 
[log.txt](https://github.com/user-attachments/files/16154454/log.txt)

**Comment by oathdruid** [comment]
版本兼容性本身应该从3.x到新的25.x/26.x/27.x应该都是可以用的；自带的cmake pipeline用ubuntu22.04的自带apt的libprotobuf-dev看起来也是work的，比如这个
https://github.com/baidu/babylon/actions/runs/9775336586/job/26985507641

单从报错看，感觉像是环境用的protoc和实际的protobuf include/lib没配套，会不会是环境有两个protobuf，用了某一套protoc，但是lib和include用了另一个的

可以打开看看生成的pb.h里面记录的版本信息，和预计使用的lib是否一致？
