### ISSUE TITLE
add_vertex和ApplicationContext结合使用

### ISSUE THREAD

**Issue by yefengdanqing** [baidu/babylon#42]
你好，我想 在add_vertex的时候通过工厂或者其他方式添加，看到有支持ApplicationContext，这两个怎么结合使用呢？？

**Comment by yefengdanqing** [comment]
{
        auto& v = builder.add_vertex([]{
            return std::make_unique<PlusProcessor>();
        });
        v.named_depend("x").to("A");
        v.named_depend("y").to("B");
        v.named_emit("z").to("C");
    }

**Comment by oathdruid** [comment]
内部版本确实是集成的ApplicationContext功能的，最近刚把ApplicationContext本身开源出来，对应的功能现在应该也具备挪出来的条件了；我看看怎么弄下，内部的使用是类似这样的

```
GraphBuilder builder;
...
builder.add_vertex("name_in_context");

BABYLON_REGISTER_COMPONENT(CustomProcessor, "name_in_context", GraphProcessor);
```

**Comment by yefengdanqing** [comment]
vertex_builder_ptr = &builder.add_vertex([] {
    auto request_processor = ApplicationContext::instance().get<GraphProcessor>("ParseRequestProcessor");
    return std::unique_ptr<GraphProcessor>(request_processor);
});

**Comment by yefengdanqing** [comment]
vertex_builder_ptr = &builder.add_vertex([] {
auto request_processor = ApplicationContext::instance().get("注册的名字");
return std::unique_ptr(request_processor);
});为啥这样获取了之后，build的时候会有问题？

**Comment by oathdruid** [comment]
get是获取单例，单例不能放到unique_ptr里面托管
ApplicationContext也有create接口，会使用工厂模式

```c++
vertex_builder_ptr = &builder.add_vertex([] {
auto request_processor = ApplicationContext::instance(). component_accessor().create<GraphProcessor>("注册的名字").release();
return std::unique_ptr(request_processor);
});
```
