### ISSUE TITLE
feat: support CMake

### ISSUE THREAD

**Issue by zhyncs** [baidu/babylon#5]
Hi Genius Li @oathdruid  Currently many open-source C++ projects support CMake. Does this project have plans to support it? When I was at Baidu before, I learned a lot from this repository. Thank you very much!

**Comment by oathdruid** [comment]
The selection of Bazel as the native build system was primarily motivated by its built-in dependency management capabilities. Additionally, The overall tool's style and emphasis on reproducibility also make it easier to align with Baidu's internal build system.

However, it's true that CMake remains a popular choice among open source projects. Providing additional CMake support would undoubtedly facilitate its wider adoption and application.

I will look into this and prepare a draft. Hoping for a CMake expert to help elevate to production-level.

**Comment by oathdruid** [comment]
@zhyncs I've tried to learn and write a CMakeList.txt draft. But not sure whether it fits general use cases. Could you please help me review it?

**Comment by zhyncs** [comment]
> @zhyncs I've tried to learn and write a CMakeList.txt draft. But not sure whether it fits general use cases. Could you please help me review it?

Hi @oathdruid Thanks for your pull request. I will review it as soon as possible.
