### ISSUE TITLE
Ubuntu 编译1.4.1有报错

### ISSUE THREAD

**Issue by sikey647** [baidu/babylon#71]
环境：
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

cmake构建：
cmake .. -DBUILD_SHARED_LIBS=1
make -j
[make_err.txt](https://github.com/user-attachments/files/17585315/make_err.txt)

**Comment by sikey647** [comment]
后来强制关闭测试构建 set(BUILD_TESTING OFF CACHE BOOL "Disable building tests" FORCE)

**Comment by oathdruid** [comment]
和GCC-9有点兼容性问题，修完我打个.2吧
