### ISSUE TITLE
transient_hash_table 出core问题

### ISSUE THREAD

**Issue by sikey647** [baidu/babylon#74]
分支：71-ubuntu-compatible
core栈：见附件。
环境：
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"

core在以下地方：
#0 0x00005649997014d9 in _mm_loadu_sil28(long long _vector(2) const*) (_P=<optimized out>)
at /usr/lib/gcc/x86_64-linux-gnu/9/include/emmintrin.h:1311
#1 babylon::internal::concurrent_transient_hash_ttable::Group::Group (controls=<optimized out>,this=<optimized out>)
at /usr/local/include/babylon/concurrent/transient_hash_table.hpp:267

transient_hash_table的key是string，value是std::shared_ptr<tensorflow::TensorProto>

以为是value是nullptr导致，然后写demo赋值nullptr并没问题。

[core栈.txt](https://github.com/user-attachments/files/17605437/core.txt)

**Comment by oathdruid** [comment]
有稳定复现的case么，有的话也挂asan之类的跑一下看看更准确的现场

**Comment by sikey647** [comment]
> 有的话也挂asan之类的跑一下看看更准确的现场

好的，我试下。
